spring:
  datasource:
    url:  jdbc:h2:mem:testdb
#    url: jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: david
    password: 1234

  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false


server:
  port: 8080
